const express=require("express")
const app=express()
const cookieParser = require('cookie-parser')
var cors = require('cors')
const authroutes=require('./routers/authroutes')
const writeroutes=require('./routers/writeroutes')
const retriveroutes=require('./routers/retrive')
const updateroutes=require('./routers/updateroutes')
const deleteroutes=require('./routers/deleteroutes')
// const {requireToken,checkUser} = require('./middleware/authmiddleware')
app.use(express.json())
app.use(cookieParser())
app.use(cors())
app.use('/api',authroutes)
app.use('/api',writeroutes)
app.use('/api',retriveroutes)
app.use('/api',updateroutes)
app.use('/api',deleteroutes)
// app.get('*',checkUser)
const port=5000
app.listen(port,()=>{
    console.log(`server running on port ${port}`)
})